- name: System optimisations
  hosts: cluster
  become: yes
  tasks:
  
    - name: apt-get update
      apt:
        update_cache: yes
    
    - name: full upgrade
      apt:
        upgrade: full

    - name: EEPROM installation
      apt:
        name: rpi-eeprom
        state: latest

    - name: EEPROM update
      shell: rpi-eeprom-update -a

    - name: autoremove
      shell: apt-get autoremove --purge -y snapd gnome-software-plugin-snap

    - name: stop snapd
      shell: apt-mark hold snapd

    - name: remove deps
      apt:
        autoremove: yes

    - name: clean deps
      apt:
        autoclean: yes